[[plugins]]
 repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

#### React(jsx) ####
# syntax highlight
[[plugins]]
repo = 'othree/yajs.vim'

# syntax highlight
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'

# closetag
[[plugins]]
repo = 'rchaser53/insertclosetag'

####################

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

#[[plugins]]
#repo = 'zxqfl/tabnine-vim'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'leafgarland/typescript-vim'
